### ISSUE TITLE
OSS の一覧を TKG 関連にする

### ISSUE THREAD

**Issue by ssekimoto** [tuna-jp/tanzu-community-site#5]
- 対象とするOSSの修正を行う
- レイアウトの修正も合わせて

**Comment by iwaseyusuke** [comment]
まずは下記
- k8s
- Buildpacks
- Harbor
- Contour
- Cluster API
- velero
- sonobuoy
- octant
- antrea
- pinniped
- carvel

**Comment by ssekimoto** [comment]
TCEを追加してください
